name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tmt
        run: pipx install tmt
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build local image
        run: ./ci_test.sh build-local-image
      - name: Set up test environment
        run: ./ci_test.sh prepare
      - name: Execute tests
        run: ./ci_test.sh execute
