name: Continuous Integration
on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install bash git-core podman python3-pip
      - name: Install tmt
        run: |
          sudo pip install tmt
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build local image
        run: ./ci_test.sh build-local-image
      - name: Set up test environment
        run: ./ci_test.sh prepare
      - name: Execute tests
        run: ./ci_test.sh execute
